# .circleci/config.yml file
version: 2.1

jobs:
  build:            # job name
    docker:         # executor type
      - image: cimg/base:current # Docker image that installs Docker and has Git,
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: echo "No need to install anything. \n Just build and push the Docker image. :D"
      - run:
          name: Build and push Docker image
          command: |
            echo "Inside the Build and push Docker image step"
            docker --version # print the version for logging
            docker build -t sudkul/sample-express-app .        
            docker tag sudkul/sample-express-app wlink69/repo-for-circle-ci:1.0.0
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push wlink69/repo-for-circle-ci:1.0.0